export const PRODUCT_NAMES = [
  {
    id: 1,
    value: "id",
  },
  {
    id: 2,
    value: "이름",
  },
  {
    id: 3,
    value: "종류",
  },
  {
    id: 4,
    value: "기간/횟수",
  },
  {
    id: 5,
    value: "가격",
  },
  {
    id: 6,
    value: "판매 여부",
  },
  {
    id: 7,
    value: "상품수정",
  },
];

export const PRODUCT_CONTENTS = [
  {
    id: 1,
    name: "그룹레슨 3개월",
    type: "패키지",
    period: "3개월",
    number: 24,
    price: 440000,
    saleOrNot: "판매중",
  },
  {
    id: 2,
    name: "개인레슨 6개월",
    type: "패키지",
    period: "6개월",
    number: 48,
    price: 1320000,
    saleOrNot: "판매중",
  },
  {
    id: 3,
    name: "헬스 이용권 3개월",
    type: "시설이용",
    period: "3개월",
    number: 0,
    price: 170000,
    saleOrNot: "판매중지",
  },
  {
    id: 4,
    name: "헬스 이용권 3개월",
    type: "시설이용",
    period: "3개월",
    number: 0,
    price: 170000,
    saleOrNot: "판매중지",
  },
  {
    id: 5,
    name: "헬스 이용권 3개월",
    type: "시설이용",
    period: "3개월",
    number: 0,
    price: 170000,
    saleOrNot: "판매중지",
  },
  {
    id: 6,
    name: "헬스 이용권 3개월",
    type: "시설이용",
    period: "3개월",
    number: 0,
    price: 170000,
    saleOrNot: "판매중지",
  },
  {
    id: 7,
    name: "헬스 이용권 3개월",
    type: "시설이용",
    period: "3개월",
    number: 0,
    price: 170000,
    saleOrNot: "판매중지",
  },
  {
    id: 8,
    name: "헬스 이용권 3개월",
    type: "시설이용",
    period: "3개월",
    number: 0,
    price: 170000,
    saleOrNot: "판매중지",
  },
  {
    id: 9,
    name: "헬스 이용권 3개월",
    type: "시설이용",
    period: "3개월",
    number: 0,
    price: 170000,
    saleOrNot: "판매중지",
  },
  {
    id: 10,
    name: "헬스 이용권 3개월",
    type: "시설이용",
    period: "3개월",
    number: 0,
    price: 170000,
    saleOrNot: "판매중지",
  },
  {
    id: 11,
    name: "헬스 이용권 3개월",
    type: "시설이용",
    period: "3개월",
    number: 0,
    price: 170000,
    saleOrNot: "판매중지",
  },
  {
    id: 12,
    name: "헬스 이용권 3개월",
    type: "시설이용",
    period: "3개월",
    number: 0,
    price: 170000,
    saleOrNot: "판매중지",
  },
];
